### ISSUE TITLE
Release on conda-forge?

### ISSUE THREAD

**Issue by jchodera** [OpenFreeEnergy/arsenic#27]
Since this codebase doesn't depend on any exclusively-omnia packages, it would be great if we could get this deployed via conda-forge and/or pip!

**Comment by mikemhenry** [comment]
Good idea!

Right now there seems to be a name collision with this package:
https://pypi.org/project/arsenic/

So if we want to be on conda-forge with the name `arsenic` it will be a race.

Would you like me to get this package on conda-forge?

**Comment by mikemhenry** [comment]
@glass-w Will take care of this

**Comment by mikemhenry** [comment]
Done!
https://github.com/conda-forge/arsenic-feedstock/
